// File: idex_pipl.v
// Generated by MyHDL 0.11
// Date: Mon May 31 10:41:03 2021


`timescale 1ns/10ps

module idex_pipl (
    reset,
    idex_reg,
    instruction,
    pc
);


input reset;
output [120:0] idex_reg;
reg [120:0] idex_reg;
input [31:0] instruction;
input [31:0] pc;




always @(instruction, reset, pc) begin: IDEX_PIPL_ID_EX
    if ((reset == 1)) begin
        idex_reg[(32 + 32)-1:32] = pc;
        idex_reg[32-1:0] = instruction;
    end
end

endmodule
