// File: pc_adder.v
// Generated by MyHDL 0.11
// Date: Mon Dec 28 14:44:59 2020


`timescale 1ns/10ps

module pc_adder (
    reset,
    step,
    pc,
    pc_addr
);


input reset;
input [0:0] step;
input [31:0] pc;
output [31:0] pc_addr;
reg [31:0] pc_addr;




always @(posedge step) begin: PC_ADDER_PADDER
    if ((reset == 1)) begin
        pc_addr <= (pc + 1);
    end
end

endmodule
