// File: wda_mux.v
// Generated by MyHDL 0.11
// Date: Mon Dec 28 14:44:59 2020


`timescale 1ns/10ps

module wda_mux (
    reset,
    wda,
    mem_to_rgs,
    result,
    read_data
);


input reset;
output [31:0] wda;
reg [31:0] wda;
input [0:0] mem_to_rgs;
input [31:0] result;
input [31:0] read_data;




always @(result, mem_to_rgs, read_data, reset) begin: WDA_MUX_WMUX
    if ((reset == 1)) begin
        if (mem_to_rgs) begin
            wda = read_data;
        end
        else begin
            wda = result;
        end
    end
end

endmodule
